# Imagen base
FROM ubuntu:20.04

ARG ESP_IDF_VERSION
ARG TARGET
ARG DEBIAN_FRONTEND=noninteractive

ENV IDF_PATH /home/esp/esp-idf
ENV PATH /home/esp/esp-idf/tools:$PATH
# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        apt-utils \
        git \
        wget \
        flex \
        bison \
        gperf \
        python3 \
        python3-venv \
        cmake \
        ninja-build \
        ccache \
        libffi-dev \
        libssl-dev \
        dfu-util \
        libusb-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash esp

USER esp
# Install ESP-IDF toolchain
WORKDIR /home/esp

# Clone ESP-IDF repository
RUN git clone -b ${ESP_IDF_VERSION} --recursive https://github.com/espressif/esp-idf.git esp-idf \
    && ./esp-idf/install.sh ${TARGET}

CMD [ "bash" ]
