name: Codacy Analysis CLI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'main/*'
      - 'components/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: analysis-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          #tool: <CLIENT_SIDE_TOOL_NAME>
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
          verbose: true
          #clang-tidy-output: 