name: Build and Upload to Board

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'main/*'
      - 'components/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_upload:
    name: "Build-Upload"
    runs-on: self-hosted    
    steps:    
      - name: Checkout
        uses: actions/checkout@v3
      - name: build project and Flash to board
        run: |
          . $IDF_PATH/export.sh
          idf.py build
          idf.py -p /dev/ttyUSB0 flash

